from django.urls import include, re_path, path

from . import views

# Create URLs associated with some of the functions found in views.py 'views_FUNCTION NAME'. You can look up what each function renders in views.py. URLs are referenced in webcdi/urls.py
urlpatterns = [
    path(
        "background/<int:pk>/",
        include(
            [
                path(
                    "",
                    views.BackgroundInfoView.as_view(),
                    name="background-info",
                ),
                path(
                    "backpage/",
                    views.BackpageBackgroundInfoView.as_view(),
                    name="backpage-background-info",
                ),
            ]
        ),
    ),
    path(
        "background/create/<int:study_id>/",
        include(
            [
                path(
                    "bypass/<slug:source_id>/",
                    views.CreateBackgroundInfoView.as_view(),
                    {"bypass": True},
                    name="create-new-background-info",
                ),
                path(
                    "<slug:source_id>/",
                    views.CreateBackgroundInfoView.as_view(),
                    {"bypass": None},
                    name="create-new-background-info",
                ),
                path(
                    "bypass/",
                    views.CreateBackgroundInfoView.as_view(),
                    {"bypass": True},
                    name="create-new-background-info",
                ),
            ]
        ),
    ),
    re_path(
        r"^fill/(?P<hash_id>[0-9a-f]{64})/$",
        views.administer_cdi_form,
        name="administer_cdi_form",
    ),
    re_path(r"^save_answer/$", views.save_answer, name="save_answer"),
    re_path(
        r"^group/(?P<username>[^/]+)/(?P<study_group>[a-zA-Z0-9-_]+)/$",
        views.find_paired_studies,
        name="find_paired_studies",
    ),
    re_path(
        r"^update_administration_data_item/$",
        views.update_administration_data_item,
        name="update-administration-data-item",
    ),
    path(
        "cat/",
        include(("cdi_forms.cat_forms.urls", "cat_forms"), namespace="cat_forms"),
    ),
    path(
        "administration/<int:pk>/",
        include(
            [
                path(
                    "pdf/",
                    views.PDFAdministrationDetailView.as_view(),
                    name="administration-pdf-view",
                ),
                path(
                    "view/",
                    views.AdministrationDetailView.as_view(),
                    name="administration-view",
                ),
            ]
        ),
    ),
    path(
        "administration/<str:hash_id>/",
        include(
            [
                path(
                    "instructions/",
                    views.InstructionDetailView.as_view(),
                    name="instructions",
                ),
                path(
                    "first-page/",
                    views.AdministrationUpdateView.as_view(),
                    name="update_administration",
                ),
                path(
                    "<int:section>/",
                    views.AdministrationUpdateView.as_view(),
                    name="update_administration_section",
                ),
                path(
                    "<int:section>/<str:previous>/",
                    views.AdministrationUpdateView.as_view(),
                    name="update_administration_section_previous",
                ),
                path(
                    "summary/",
                    views.AdministrationSummaryView.as_view(),
                    name="administration_summary_view",
                ),
                path(
                    "contact/",
                    views.AdministrationContactView.as_view(),
                    name="contact",
                ),
            ]
        ),
    ),
]
