# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_UI', '0021_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='prefilled_data',
            field=models.IntegerField(default=0),
        ),
    ]
