# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_UI", "0022_study_prefilled_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="max_age",
            field=models.IntegerField(
                blank=True, null=True, verbose_name=b"Maximum age"
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="min_age",
            field=models.IntegerField(
                blank=True, null=True, verbose_name=b"Minimum age"
            ),
        ),
    ]
