# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_UI', '0023_auto_20171221_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='birth_weight_units',
            field=models.CharField(default=b'lb', max_length=5),
        ),
    ]
