# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-27 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_UI', '0024_study_birth_weight_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='show_feedback',
            field=models.BooleanField(default=True),
        ),
    ]
