# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-28 23:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('researcher_UI', '0025_study_show_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=101, verbose_name=b'Name of institution')),
                ('position', models.CharField(max_length=101, verbose_name=b'Position in Institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
