# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_UI', '0027_study_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Administration Summary',
                'proxy': True,
                'verbose_name_plural': 'Administration Summary',
                'indexes': [],
            },
            bases=('researcher_UI.administration',),
        ),
    ]
