# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 08:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_UI', '0028_administrationsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='test_period',
            field=models.IntegerField(default=14, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
    ]
