# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 12:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_UI", "0029_auto_20190524_0853"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstrumentScore",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=101)),
                ("category", models.CharField(max_length=101)),
                ("measure", models.CharField(max_length=101)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="researcher_UI.instrument",
                    ),
                ),
            ],
        ),
    ]
