# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_UI", "0030_instrumentscore"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instrumentscore",
            options={"ordering": ["instrument", "order"]},
        ),
        migrations.AddField(
            model_name="instrumentscore",
            name="order",
            field=models.IntegerField(default=999),
        ),
    ]
