# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_UI", "0031_auto_20190530_0807"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrumentscore",
            name="kind",
            field=models.CharField(
                choices=[("count", "count"), ("list", "list")],
                default="count",
                max_length=5,
            ),
        ),
    ]
