# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_UI', '0032_instrumentscore_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='allowed_instruments',
            field=models.ManyToManyField(blank=True, to='researcher_UI.instrument', verbose_name='Instruments this researcher has access to'),
        ),
    ]
