# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-02 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_UI', '0034_benchmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benchmark',
            options={'ordering': ['instrument_score', 'age', 'raw_score']},
        ),
        migrations.RenameField(
            model_name='benchmark',
            old_name='raw_score_boy',
            new_name='percentile_boy',
        ),
        migrations.RenameField(
            model_name='benchmark',
            old_name='raw_score_girl',
            new_name='percentile_girl',
        ),
    ]
