# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-05 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_UI", "0036_auto_20190621_0742"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="benchmark",
            options={"ordering": ["instrument_score", "age", "percentile"]},
        ),
        migrations.AddField(
            model_name="administration",
            name="local_lab_id",
            field=models.CharField(blank=True, max_length=101, null=True),
        ),
    ]
