# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-01 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_UI', '0036_auto_20190621_0742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benchmark',
            options={'ordering': ['instrument_score', 'age', 'percentile']},
        ),
    ]
