# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-02 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_UI', '0037_auto_20190801_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='completedSurvey',
            field=models.BooleanField(default=False),
        ),
    ]
