# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-12 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_UI", "0037_auto_20190805_0645"),
        ("researcher_UI", "0038_administration_completedsurvey"),
    ]

    operations = []
