# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-09-29 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_UI", "0039_merge_20190812_1054"),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="waiver",
            field=models.TextField(blank=True),
        ),
    ]
