# Generated by Django 2.2.6 on 2019-10-04 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_UI', '0041_auto_20190929_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='analysis',
            field=models.NullBooleanField(default=None, verbose_name='Confirmed Age and Completion'),
        ),
        migrations.AlterField(
            model_name='administration',
            name='bypass',
            field=models.NullBooleanField(default=None, verbose_name='Willing to forgo payment'),
        ),
        migrations.AlterField(
            model_name='administration',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='administration',
            name='due_date',
            field=models.DateTimeField(verbose_name='Expiration date'),
        ),
        migrations.AlterField(
            model_name='administration',
            name='include',
            field=models.NullBooleanField(default=True, verbose_name='Include for eventual analysis'),
        ),
        migrations.AlterField(
            model_name='administration',
            name='page_number',
            field=models.IntegerField(default=0, verbose_name='Page number'),
        ),
        migrations.AlterField(
            model_name='administration',
            name='repeat_num',
            field=models.IntegerField(verbose_name='Administration number'),
        ),
        migrations.AlterField(
            model_name='administration',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher_UI.study'),
        ),
        migrations.AlterField(
            model_name='administration_data',
            name='administration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher_UI.administration'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='max_age',
            field=models.IntegerField(verbose_name='Maximum age'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='min_age',
            field=models.IntegerField(verbose_name='Minimum age'),
        ),
        migrations.AlterField(
            model_name='ip_address',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date IP address was added to database'),
        ),
        migrations.AlterField(
            model_name='ip_address',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher_UI.study'),
        ),
        migrations.AlterField(
            model_name='payment_code',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date code was added to database'),
        ),
        migrations.AlterField(
            model_name='payment_code',
            name='assignment_date',
            field=models.DateTimeField(null=True, verbose_name='Date code was given to participant'),
        ),
        migrations.AlterField(
            model_name='payment_code',
            name='gift_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Monetary value'),
        ),
        migrations.AlterField(
            model_name='payment_code',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher_UI.study'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='institution',
            field=models.CharField(max_length=101, verbose_name='Name of Institution'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='position',
            field=models.CharField(max_length=101, verbose_name='Position in Institution'),
        ),
        migrations.AlterField(
            model_name='study',
            name='birth_weight_units',
            field=models.CharField(default='lb', max_length=5),
        ),
        migrations.AlterField(
            model_name='study',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher_UI.instrument'),
        ),
        migrations.AlterField(
            model_name='study',
            name='max_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum age'),
        ),
        migrations.AlterField(
            model_name='study',
            name='min_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum age'),
        ),
        migrations.AlterField(
            model_name='study',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
