# Generated by Django 2.2.6 on 2020-01-20 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_UI", "0042_auto_20191004_1238"),
    ]

    operations = [
        migrations.CreateModel(
            name="SummaryData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                (
                    "administration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="researcher_UI.administration",
                    ),
                ),
            ],
            options={
                "ordering": ["administration"],
                "unique_together": {("administration", "title")},
            },
        ),
    ]
