# Generated by Django 2.2.6 on 2020-01-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_UI", "0043_summarydata"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="timing",
            field=models.IntegerField(default=6),
        ),
    ]
