# Generated by Django 2.2.6 on 2020-02-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_UI", "0044_study_timing"),
    ]

    operations = [
        migrations.AddField(
            model_name="administration",
            name="opt_out",
            field=models.NullBooleanField(
                default=None, verbose_name="Participant opted out of broader sharing"
            ),
        ),
    ]
