# Generated by Django 2.2.6 on 2020-04-21 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_UI", "0047_study_confirmation_questions"),
        ("researcher_UI", "0049_instrumentscore_scoring_measures"),
    ]

    operations = []
