# Generated by Django 2.2.6 on 2020-05-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_UI", "0051_auto_20200501_0746"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="prolific_boolean",
            field=models.BooleanField(default=False),
        ),
    ]
