# Generated by Django 2.2.13 on 2020-06-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_UI", "0052_study_prolific_boolean"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="backpage_boolean",
            field=models.BooleanField(
                default=True,
                help_text="When selected the final demographics page will be shown - deselect to not show the final page",
            ),
        ),
    ]
