# Generated by Django 2.2.13 on 2020-06-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_UI", "0052_study_prolific_boolean"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="print_my_answers_boolean",
            field=models.BooleanField(default=True),
        ),
    ]
