# Generated by Django 2.2.13 on 2020-09-16 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_UI', '0054_auto_20200821_1132'),
        ('researcher_UI', '0053_study_backpage_boolean'),
    ]

    operations = [
    ]
