# Generated by Django 2.2.13 on 2020-12-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_UI", "0057_auto_20201204_0933"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="demographics",
            field=models.ManyToManyField(to="researcher_UI.Demographic"),
        ),
    ]
