# Generated by Django 2.2.13 on 2020-12-04 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_UI', '0058_study_demographics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='demographics',
        ),
        migrations.AddField(
            model_name='instrument',
            name='demographics',
            field=models.ManyToManyField(to='researcher_UI.Demographic'),
        ),
        migrations.AddField(
            model_name='study',
            name='demographic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researcher_UI.Demographic'),
        ),
    ]
