# Generated by Django 3.2.18 on 2023-03-03 14:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("researcher_UI", "0066_auto_20221210_0644"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instrument",
            options={"ordering": ["verbose_name"]},
        ),
        migrations.AlterField(
            model_name="study",
            name="waiver",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, verbose_name="Opening Dialog Box"
            ),
        ),
    ]
