# Generated by Django 3.2.18 on 2023-04-03 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_UI', '0068_instrumentfamily'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researcher_UI.instrumentfamily'),
        ),
    ]
