# Generated by Django 3.2.18 on 2023-04-09 17:51

import datetime

from brookes.models import BrookesCode
from django.db import migrations, models
from django.utils import timezone
from researcher_UI.models import researcher as Researcher


def update_researchers(apps, schema_editor):
    for researcher in Researcher.objects.all():
        for instrument in researcher.allowed_instruments.all():
            if (
                instrument.family
                and not instrument.family
                in researcher.allowed_instrument_families.all()
            ):
                try:
                    researcher.allowed_instrument_families.add(instrument.family)
                    if instrument.family.chargeable:
                        b = BrookesCode(
                            researcher=researcher.user,
                            instrument_family=instrument.family,
                            applied=timezone.now(),
                            expiry=datetime.datetime.strptime(
                                "2023-05-31", "%Y-%m-%d"
                            ).date(),
                        )
                        b.save()
                except Exception as e:
                    print(
                        f"Failed to add family for instrument {instrument} to {researcher.user}.  Error {e}"
                    )


class Migration(migrations.Migration):
    dependencies = [
        ("researcher_UI", "0071_alter_instrumentfamily_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="share_opt_out",
            field=models.BooleanField(
                default=False,
                help_text="For chargeable instruments you may opt out of sharing the study data.  Selecting this will have no impact on non-chargeable instruments",
            ),
        ),
        migrations.RunPython(update_researchers),
    ]
