# Generated by Django 3.2.18 on 2023-04-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_UI', '0073_auto_20230410_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='scored',
            field=models.BooleanField(default=False),
        ),
    ]
