# Generated by Django 3.2.19 on 2023-06-27 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_UI", "0074_administration_scored"),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="test_period",
            field=models.IntegerField(
                default=14,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1095),
                ],
            ),
        ),
    ]
