# Generated by Django 3.2.19 on 2023-06-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_UI', '0074_administration_scored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmark',
            name='raw_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='benchmark',
            name='raw_score_boy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='benchmark',
            name='raw_score_girl',
            field=models.FloatField(),
        ),
    ]
