# Generated by Django 3.2.20 on 2023-08-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_UI", "0075_alter_study_test_period"),
        ("researcher_UI", "0075_auto_20230614_0806"),
    ]

    operations = []
