# Generated by Django 3.2.20 on 2023-08-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_UI", "0076_merge_20230807_0943"),
    ]

    operations = [
        migrations.AddField(
            model_name="administration",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
