# Generated by Django 3.2.20 on 2023-08-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_UI', '0080_auto_20230816_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='allowed_instruments',
            field=models.ManyToManyField(blank=True, to='researcher_UI.Instrument', verbose_name='Instruments this researcher has access to'),
        ),
    ]
