# Generated by Django 3.2.20 on 2023-09-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_UI', '0092_auto_20230904_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='completion_data',
            field=models.JSONField(blank=True, help_text='Data to be included in the completion url.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='allowed_instruments',
            field=models.ManyToManyField(blank=True, to='researcher_UI.Instrument', verbose_name='Instruments this researcher has access to'),
        ),
    ]
