# Generated by Django 4.2.8 on 2024-02-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_UI", "0001_squashed_0094_auto_20230904_0938"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administration",
            name="completed",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="administration",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="instrumentscore",
            name="scoring_measures",
            field=models.CharField(max_length=101),
        ),
        migrations.AlterField(
            model_name="payment_code",
            name="payment_type",
            field=models.CharField(
                choices=[("Amazon", "Amazon"), ("Tango", "Tango")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="demographic_opt_out",
            field=models.BooleanField(
                default=False,
                help_text="For chargeable instruments you may opt out of collecting demographic data.  We will still collect age, sex and whether born early or late for norming purposes",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="no_demographic_boolean",
            field=models.BooleanField(
                default=False,
                help_text="You must include DOB, age offset and sex in the Link URL for norming purposes.  Only select this is this data will be provided in the link.",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="participant_source_boolean",
            field=models.IntegerField(
                choices=[
                    (0, "None"),
                    (1, "Prolific"),
                    (3, "RedCap"),
                    (4, "Lookit"),
                    (5, "Mturk"),
                    (6, "Qualtrics"),
                    (99, "Other"),
                ],
                default=0,
            ),
        ),
    ]
