# Generated by Django 4.2.10 on 2024-02-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_UI', '0096_rename_payment_code_paymentcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcode',
            name='payment_type',
            field=models.CharField(choices=[('Amazon', 'Amazon'), ('Tango', 'Tango')], max_length=151),
        ),
    ]
