# Generated by Django 4.2.10 on 2024-02-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_UI', '0097_alter_paymentcode_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcode',
            name='gift_code',
            field=models.CharField(max_length=151),
        ),
        migrations.AlterField(
            model_name='paymentcode',
            name='payment_type',
            field=models.CharField(choices=[('Amazon', 'Amazon'), ('Tango', 'Tango')], max_length=50),
        ),
    ]
