# Generated by Django 4.2.16 on 2025-01-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_UI", "0098_alter_paymentcode_gift_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demographic",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
