# Generated by Django 4.2.20 on 2025-04-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_UI", "0099_alter_demographic_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="administration",
            name="send_completion_flag_url_response",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
