# Generated by Django 4.2.20 on 2025-06-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_UI", "0101_study_single_reuseable_link_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="study",
            old_name="single_reuseable_link_active",
            new_name="single_reusable_link_active",
        ),
    ]
