# Generated by Django 4.2.28 on 2026-03-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "researcher_UI",
            "0102_rename_single_reuseable_link_active_study_single_reusable_link_active",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="redirect_button_text",
            field=models.CharField(
                blank=True,
                help_text="Specify Redirect Button text here",
                max_length=40,
                null=True,
                verbose_name="Custom Text for Reidrect Button",
            ),
        ),
        migrations.AddField(
            model_name="study",
            name="redirect_button_type",
            field=models.BooleanField(
                default=False,
                help_text="Change to Custom if you want to specify the text in the redirect button",
                verbose_name="Type of Text for Redirect Button",
            ),
        ),
    ]
