# Generated by Django 4.2.28 on 2026-03-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_UI", "0103_study_redirect_button_text_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="study",
            old_name="redirect_button_type",
            new_name="redirect_button_boolean",
        ),
    ]
