# Generated by Django 4.2.28 on 2026-03-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "researcher_UI",
            "0104_rename_redirect_button_type_study_redirect_button_boolean",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="study",
            old_name="redirect_button_boolean",
            new_name="custom_redirect_button_boolean",
        ),
        migrations.RenameField(
            model_name="study",
            old_name="redirect_button_text",
            new_name="custom_redirect_button_text",
        ),
    ]
