# Generated by Django 4.2.28 on 2026-03-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "researcher_UI",
            "0105_rename_redirect_button_boolean_study_custom_redirect_button_boolean_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="show_my_answers_boolen",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="study",
            name="custom_redirect_button_boolean",
            field=models.BooleanField(
                default=False,
                help_text="Select if you want Bespoke Text",
                verbose_name="Use Bespoke Text for Redirect Button",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="custom_redirect_button_text",
            field=models.CharField(
                blank=True,
                help_text="Specify Redirect Button text here",
                max_length=40,
                null=True,
                verbose_name="Custom Text for Redirect Button",
            ),
        ),
    ]
