# Generated by Django 4.2.28 on 2026-04-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_UI", "0106_study_show_my_answers_boolen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="required_source_id",
            field=models.BooleanField(
                default=False, verbose_name="Is source id a required field?"
            ),
        ),
    ]
