version: '3.7'

services:
  db:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - "5432"
      healthcheck:
        test: "exit 0"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./webcdi:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      
  mail:
    platform: linux/x86_64
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - db
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: always

volumes:
  postgres_data: