# Generated by Django 4.2.8 on 2023-12-12 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import brookes.utils


class Migration(migrations.Migration):

    replaces = [
        ("brookes", "0001_initial"),
        ("brookes", "0002_alter_brookescode_code"),
        ("brookes", "0003_alter_brookescode_instrument"),
        ("brookes", "0004_rename_instrument_brookescode_instrument_family"),
        ("brookes", "0005_brookescode_expiry"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("researcher_UI", "0067_auto_20230303_1432"),
        ("researcher_UI", "0071_alter_instrumentfamily_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrookesCode",
            fields=[
                (
                    "code",
                    models.CharField(
                        default=brookes.utils.create_brookes_code,
                        max_length=15,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("applied", models.DateTimeField(blank=True, null=True)),
                (
                    "instrument_family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="researcher_UI.instrumentfamily",
                    ),
                ),
                (
                    "researcher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("expiry", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
