# Generated by Django 3.2.18 on 2023-03-17 17:17

import brookes.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brookes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brookescode",
            name="code",
            field=models.CharField(
                default=brookes.utils.create_brookes_code,
                max_length=15,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
