# Generated by Django 3.2.18 on 2023-04-05 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_UI', '0071_alter_instrumentfamily_options'),
        ('brookes', '0002_alter_brookescode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brookescode',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='researcher_UI.instrumentfamily'),
        ),
    ]
