# Generated by Django 3.2.18 on 2023-04-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brookes", "0003_alter_brookescode_instrument"),
    ]

    operations = [
        migrations.RenameField(
            model_name="brookescode",
            old_name="instrument",
            new_name="instrument_family",
        ),
    ]
