/**
 * Validates the BUILT bundle (static/cdi_forms/cat/webcdi-cat.js) against
 * mirtCAT ground-truth sequences generated by the production R code path.
 *
 * Ground truth: CSVs with columns index,item,response,theta — one row per
 * administered item, produced by gen_sequences.R (mirtCAT, criteria='MI',
 * method='ML', min 25 / max 50 items, min SEM 0.15). Set GROUND_TRUTH_DIR
 * to point at them; defaults to ./ground_truth.
 *
 * Pass criteria per sequence:
 *  - the engine proposes the same item as mirtCAT at every step,
 *  - theta matches within 0.01 at every step,
 *  - the engine stops exactly where mirtCAT stopped.
 */
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";

// evaluate the IIFE in global scope so its top-level var lands on globalThis
vm.runInThisContext(
  fs.readFileSync(
    path.join(import.meta.dirname, "../../static/cdi_forms/cat/webcdi-cat.js"),
    "utf8"
  )
);
const { createEngine } = globalThis.WebCDICat;

const GT_DIR = process.env.GROUND_TRUTH_DIR || path.join(import.meta.dirname, "ground_truth");
const BANK_DIR = path.join(import.meta.dirname, "../../static/cdi_forms/cat");

function parseCSV(text) {
  const rows = [];
  let cur = "", row = [], inQ = false;
  for (const ch of text) {
    if (ch === '"') inQ = !inQ;
    else if (ch === "," && !inQ) { row.push(cur); cur = ""; }
    else if (ch === "\n" && !inQ) { row.push(cur); cur = ""; if (row.length > 1 || row[0] !== "") rows.push(row); row = []; }
    else if (ch !== "\r" || inQ) cur += ch;
  }
  if (cur !== "" || row.length) { row.push(cur); rows.push(row); }
  const header = rows[0];
  return rows.slice(1).map((r) => Object.fromEntries(header.map((h, i) => [h, r[i]])));
}

let allPass = true;
const files = fs.readdirSync(GT_DIR).filter((f) => f.endsWith(".csv")).sort();
if (!files.length) {
  console.error(`no ground-truth CSVs found in ${GT_DIR}`);
  process.exit(1);
}
for (const f of files) {
  const lang = f.split("_")[0];
  const params = JSON.parse(fs.readFileSync(path.join(BANK_DIR, `${lang}.json`), "utf8"));
  const seq = parseCSV(fs.readFileSync(path.join(GT_DIR, f), "utf8"));

  const engine = createEngine(params, { items: [], responses: [] });
  let maxThetaDiff = 0, selectionMisses = 0, stoppedEarly = false;

  const badRow = seq.find((r) => !(parseInt(r.index) >= 1));
  if (badRow) {
    console.log(`FAIL  ${f}: unparseable row ${JSON.stringify(badRow)}`);
    allPass = false;
    continue;
  }

  for (let i = 0; i < seq.length; i++) {
    engine.record(parseInt(seq[i].index), parseInt(seq[i].response));
    const out = engine.next();
    maxThetaDiff = Math.max(maxThetaDiff, Math.abs(out.curTheta - parseFloat(seq[i].theta)));
    const isLast = i === seq.length - 1;
    if (isLast) {
      if (!out.stop) { selectionMisses++; console.log(`  ${f}: engine did not stop where mirtCAT stopped (n=${seq.length})`); }
    } else {
      if (out.stop) { stoppedEarly = true; console.log(`  ${f}: engine stopped early at n=${i + 1}`); break; }
      const expected = parseInt(seq[i + 1].index);
      if (out.index !== expected) {
        // near-ties in Fisher information can flip on the ~1e-4 theta
        // difference between estimators; accept picks within 0.5% of
        // the information of mirtCAT's pick
        const fiOf = (idx) => {
          const { a, b, c, d } = params.items.find((it) => it.index === idx);
          const e = Math.exp(-a * (out.curTheta - b));
          const p = c + (d - c) / (1 + e);
          const pp = (a * (d - c) * e) / ((1 + e) * (1 + e));
          return (pp * pp) / (p * (1 - p));
        };
        const rel = Math.abs(fiOf(out.index) - fiOf(expected)) / fiOf(expected);
        if (rel < 0.005) {
          console.log(`  ${f} step ${i + 2}: near-tie (${out.index} vs ${expected}, info gap ${(rel * 100).toFixed(3)}%)`);
        } else {
          selectionMisses++;
          console.log(`  ${f} step ${i + 2}: engine chose ${out.index}, mirtCAT chose ${expected} (info gap ${(rel * 100).toFixed(2)}%)`);
        }
      }
    }
  }

  const pass = maxThetaDiff < 0.01 && selectionMisses === 0 && !stoppedEarly;
  if (!pass) allPass = false;
  console.log(`${pass ? "PASS" : "FAIL"}  ${f.padEnd(24)} steps=${seq.length}  theta<=${maxThetaDiff.toFixed(4)}`);
}
console.log(allPass ? "\nALL SEQUENCES PASS" : "\nSOME FAIL");
process.exit(allPass ? 0 : 1);
