branch-defaults:
  hebrew:
    environment: webcdi-dev-hebrew
  master:
    environment: null
    group_suffix: null
environment-defaults:
  webcdi-dev-hebrew:
    branch: null
    repository: null
global:
  application_name: web-cdi
  default_ec2_keyname: web-cdi_011017
  default_platform: Python 3.8
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: web-cdi
  sc: git
  workspace_type: Application
