# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('cdi_forms', '0038_populate_spanish_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_set', models.CharField(max_length=101)),
            ],
        ),
        migrations.AddField(
            model_name='english_wg',
            name='choices_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdi_forms.Choices'),
        ),
        migrations.AddField(
            model_name='english_ws',
            name='choices_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdi_forms.Choices'),
        ),
        migrations.AddField(
            model_name='spanish_wg',
            name='choices_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdi_forms.Choices'),
        ),
        migrations.AddField(
            model_name='spanish_ws',
            name='choices_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdi_forms.Choices'),
        )
    ]
