# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import os
import pandas as pd
from django.conf import settings

def populateChoiceModel(apps, schema_editor):
    
    PROJECT_ROOT = settings.BASE_DIR
    choices_csv_path = os.path.realpath(PROJECT_ROOT + '/cdi_form_csv/choice_options.csv')

    Choices = apps.get_model('cdi_forms', 'Choices')

    choices_data=pd.read_csv(choices_csv_path, sep=',').fillna('')

    Choices.objects.bulk_create([Choices(**vals) for vals in choices_data.to_dict('records')])

def addChoicesLink(apps, schema_editor):

    instrument_models = ['English_WS', 'English_WG', 'Spanish_WS', 'Spanish_WG']

    Choices = apps.get_model('cdi_forms', 'Choices')

    for curr_model in instrument_models:
        Instrument_model = apps.get_model('cdi_forms', curr_model)

        for curr_item in Instrument_model.objects.exclude(choices__isnull=True).exclude(choices__exact=''):
            choices_link, created = Choices.objects.get_or_create(choice_set = curr_item.choices)
            curr_item.choices_link = choices_link
            curr_item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cdi_forms', '0039_add_choices_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='choice_set_en',
            field=models.CharField(max_length=101, null=True),
        ),
        migrations.AddField(
            model_name='choices',
            name='choice_set_es',
            field=models.CharField(max_length=101, null=True),
        ),
        migrations.RunPython(populateChoiceModel),
        migrations.RunPython(addChoicesLink)
    ]
