# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-17 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdi_forms', '0043_auto_20180517_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='english_wg',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='english_ws',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='spanish_wg',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='spanish_ws',
            name='choices',
        ),
        migrations.DeleteModel(
            name='English_WG',
        ),
        migrations.DeleteModel(
            name='English_WS',
        ),
        migrations.DeleteModel(
            name='Spanish_WG',
        ),
        migrations.DeleteModel(
            name='Spanish_WS',
        ),
    ]
