# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-26 00:30
from __future__ import unicode_literals

import os

import pandas as pd
from django.conf import settings
from django.db import migrations, models


def updateChoiceModel(apps, schema_editor):

    PROJECT_ROOT = settings.BASE_DIR
    choices_csv_path = os.path.realpath(
        PROJECT_ROOT + "/cdi_form_csv/choice_options.csv"
    )

    Choices = apps.get_model("cdi_forms", "Choices")

    choices_data = pd.read_csv(choices_csv_path, sep=",").fillna("")
    choice_fields = [f.name for f in Choices._meta.get_fields()]

    for index, row in choices_data.iterrows():
        data_dict = dict(row)
        sub_dict = {
            k: data_dict.get(k, None)
            for k in set.intersection(set(data_dict.keys()), set(choice_fields))
        }
        sub_dict.pop("choice_set", None)
        Choices.objects.update_or_create(
            choice_set=row["choice_set"], defaults=sub_dict
        )


class Migration(migrations.Migration):

    dependencies = [
        ("cdi_forms", "0044_remove_original_items_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="choices",
            name="choice_set_fr",
            field=models.CharField(max_length=101, null=True),
        ),
        migrations.RunPython(updateChoiceModel),
    ]
