# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-06 20:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdi_forms', '0045_add_french_to_choices_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument_forms',
            name='item_order',
            field=models.IntegerField(default=999, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
