# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-16 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cdi_forms', '0046_instrument_forms_add_item_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundinfo',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country'),
        ),
    ]
