# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import os
import pandas as pd
from django.conf import settings

def updateChoiceModel(apps, schema_editor):
    
    PROJECT_ROOT = settings.BASE_DIR
    choices_csv_path = os.path.realpath(PROJECT_ROOT + '/cdi_form_csv/choice_options.csv')

    Choices = apps.get_model('cdi_forms', 'Choices')

    choices_data=pd.read_csv(choices_csv_path, sep=',').fillna('')
    choice_fields = [f.name for f in Choices._meta.get_fields()]

    for index, row in choices_data.iterrows():
        data_dict = dict(row)
        sub_dict = {k: data_dict.get(k, None) for k in set.intersection(set(data_dict.keys()), set(choice_fields))}
        sub_dict.pop('choice_set', None)
        Choices.objects.update_or_create(choice_set=row['choice_set'], defaults = sub_dict)

class Migration(migrations.Migration):

    dependencies = [
        ('cdi_forms', '0051_auto_20190329_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundinfo',
            name='primary_caregiver',
            field=models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('grandparent(s)', 'Grandparent(s)'), ('other', 'Other')], max_length=20, verbose_name='Primary Caregiver'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='secondary_caregiver',
            field=models.CharField(blank=True, choices=[('mother', 'Mother'), ('father', 'Father'), ('grandparent(s)', 'Grandparent(s)'), ('other', 'Other')], max_length=20, null=True, verbose_name='Secondary Caregiver'),
        ),
    ]
