# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdi_forms', '0052_auto_20190408_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='choice_set_en_ca',
            field=models.CharField(max_length=101, null=True),
        ),
    ]
