# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-01 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdi_forms', '0056_choices_choice_set_nl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundinfo',
            name='illnesses_boolean',
            field=models.IntegerField(default=-1, verbose_name='Has your child had any major illnesses, hospitalizations, or diagnosed disabilities?'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='learning_disability_boolean',
            field=models.IntegerField(default=-1, verbose_name='Have you or anyone in your immediate family been diagnosed with a language or learning disability?'),
        ),
    ]
