# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-01 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cdi_forms", "0059_auto_20190801_1616"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backgroundinfo",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                null=True,
            ),
        ),
    ]
