# Generated by Django 2.2.6 on 2019-10-04 12:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdi_forms', '0062_auto_20190929_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundinfo',
            name='administration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='researcher_UI.administration'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='age',
            field=models.IntegerField(default=999, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Age (in months)'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='child_hispanic_latino',
            field=models.NullBooleanField(verbose_name='Is your child Hispanic or Latino?'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='due_date_diff',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, 'Number of weeks cannot be less than 1')], verbose_name='By how many weeks? (round to the nearest week)'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='ear_infections',
            field=models.CharField(blank=True, max_length=1001, null=True, verbose_name='Has your child undergone interventions (e.g., tubes)?  Please describe'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='early_or_late',
            field=models.CharField(blank=True, choices=[('early', 'Early'), ('late', 'Late')], max_length=5, null=True, verbose_name='Was he/she early or late?'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='father_education',
            field=models.IntegerField(blank=True, choices=[(5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12 (High school graduate)'), (13, '13'), (14, '14'), (15, '15'), (16, '16 (College graduate)'), (17, '17'), (18, '18 (Advanced degree)'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23 or more'), (0, 'Prefer not to disclose')], help_text='Choose highest grade completed (12 = high school graduate; 16 = college graduate; 18 = advanced degree)', null=True, verbose_name='Secondary Caregiver Education'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='father_yob',
            field=models.IntegerField(blank=True, choices=[(1950, '1950'), (1951, '1951'), (1952, '1952'), (1953, '1953'), (1954, '1954'), (1955, '1955'), (1956, '1956'), (1957, '1957'), (1958, '1958'), (1959, '1959'), (1960, '1960'), (1961, '1961'), (1962, '1962'), (1963, '1963'), (1964, '1964'), (1965, '1965'), (1966, '1966'), (1967, '1967'), (1968, '1968'), (1969, '1969'), (1970, '1970'), (1971, '1971'), (1972, '1972'), (1973, '1973'), (1974, '1974'), (1975, '1975'), (1976, '1976'), (1977, '1977'), (1978, '1978'), (1979, '1979'), (1980, '1980'), (1981, '1981'), (1982, '1982'), (1983, '1983'), (1984, '1984'), (1985, '1985'), (1986, '1986'), (1987, '1987'), (1988, '1988'), (1989, '1989'), (1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (0, 'Prefer not to disclose')], null=True, verbose_name='Secondary Caregiver Year of birth'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='hearing_loss',
            field=models.CharField(blank=True, max_length=1001, null=True, verbose_name='Please describe'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='illnesses',
            field=models.CharField(blank=True, max_length=1001, null=True, verbose_name='Please describe'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='language_days_per_week',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(7, 'Number of days per week cannot exceed 7'), django.core.validators.MinValueValidator(1, 'Number of days per week cannot be less than 1')], verbose_name='How many days per week is the child exposed to these languages?'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='language_from',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='From whom?'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='language_hours_per_day',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(24, 'Number of hours per day cannot exceed 24'), django.core.validators.MinValueValidator(1, 'Number of hours per day cannot be less than 1')], verbose_name='How many hours per day is the child exposed to these languages?'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='learning_disability',
            field=models.CharField(blank=True, max_length=1001, null=True, verbose_name='Indicate which family member and provide a description'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='mother_education',
            field=models.IntegerField(blank=True, choices=[(5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12 (High school graduate)'), (13, '13'), (14, '14'), (15, '15'), (16, '16 (College graduate)'), (17, '17'), (18, '18 (Advanced degree)'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23 or more'), (0, 'Prefer not to disclose')], help_text='Choose highest grade completed (12 = high school graduate; 16 = college graduate; 18 = advanced degree)', null=True, verbose_name='Primary Caregiver Education'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='mother_yob',
            field=models.IntegerField(blank=True, choices=[(1950, '1950'), (1951, '1951'), (1952, '1952'), (1953, '1953'), (1954, '1954'), (1955, '1955'), (1956, '1956'), (1957, '1957'), (1958, '1958'), (1959, '1959'), (1960, '1960'), (1961, '1961'), (1962, '1962'), (1963, '1963'), (1964, '1964'), (1965, '1965'), (1966, '1966'), (1967, '1967'), (1968, '1968'), (1969, '1969'), (1970, '1970'), (1971, '1971'), (1972, '1972'), (1973, '1973'), (1974, '1974'), (1975, '1975'), (1976, '1976'), (1977, '1977'), (1978, '1978'), (1979, '1979'), (1980, '1980'), (1981, '1981'), (1982, '1982'), (1983, '1983'), (1984, '1984'), (1985, '1985'), (1986, '1986'), (1987, '1987'), (1988, '1988'), (1989, '1989'), (1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (0, 'Prefer not to disclose')], null=True, verbose_name='Primary Caregiver Year of birth'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='multi_birth',
            field=models.IntegerField(blank=True, choices=[(2, 'Twins'), (3, 'Triplets'), (4, 'Quadruplets'), (5, 'Quintuplets or greater')], null=True, verbose_name='Twins, triplets, quadruplets, other?'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='services',
            field=models.CharField(blank=True, max_length=1001, null=True, verbose_name='Please describe'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='vision_problems',
            field=models.CharField(blank=True, max_length=1001, null=True, verbose_name='Please describe'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='worried',
            field=models.CharField(blank=True, max_length=1001, null=True, verbose_name='Please describe'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid U.S. zip code', regex='^(\\d{3}([*]{2})?)|([A-Z]{2})$')], verbose_name='Zip Code (if you live in the U.S.)'),
        ),
        migrations.AlterField(
            model_name='instrument_forms',
            name='choices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cdi_forms.Choices'),
        ),
    ]
