# Generated by Django 2.2.6 on 2020-03-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdi_forms', '0065_auto_20200120_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundinfo',
            name='sibling_boolean',
            field=models.BooleanField(default=False, verbose_name='Does you child have siblings?'),
        ),
        migrations.AddField(
            model_name='backgroundinfo',
            name='sibling_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='How many siblings does you child have?'),
        ),
        migrations.AddField(
            model_name='backgroundinfo',
            name='sibling_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
