# Generated by Django 2.2.6 on 2020-03-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdi_forms', '0066_auto_20200329_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundinfo',
            name='sibling_boolean',
            field=models.IntegerField(default=False, verbose_name='Does you child have siblings?'),
        ),
    ]
