# Generated by Django 2.2.6 on 2020-04-09 18:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdi_forms', '0067_merge_20200407_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundinfo',
            name='child_ethnicity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), blank=True, null=True, size=None, verbose_name="Child's Ethnicity"),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='father_education',
            field=models.IntegerField(blank=True, choices=[(5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24')], help_text='Choose highest grade completed (12 = high school graduate; 16 = college graduate; 18 = advanced degree)', null=True, verbose_name='Secondary Caregiver Education'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='mother_education',
            field=models.IntegerField(blank=True, choices=[(5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24')], help_text='Choose highest grade completed (12 = high school graduate; 16 = college graduate; 18 = advanced degree)', null=True, verbose_name='Primary Caregiver Education'),
        ),
    ]
