# Generated by Django 2.2.6 on 2020-03-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdi_forms', '0067_auto_20200329_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundinfo',
            name='sibling_boolean',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Does you child have siblings?'),
        ),
    ]
