# Generated by Django 2.2.6 on 2020-04-13 07:57

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_UI', '0049_instrumentscore_scoring_measures'),
        ('cdi_forms', '0068_auto_20200409_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='choice_set_ko',
        ),
        migrations.CreateModel(
            name='CatResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administered_words', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=101), null=True, size=None)),
                ('administered_items', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('administered_responses', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), null=True, size=None)),
                ('est_theta', models.FloatField(null=True)),
                ('administration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='researcher_UI.administration')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(blank=True, max_length=1001, null=True)),
                ('discrimination', models.FloatField()),
                ('difficulty', models.FloatField()),
                ('guessing', models.FloatField()),
                ('upper_asymptote', models.FloatField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher_UI.instrument')),
            ],
            options={
                'ordering': ['definition'],
                'unique_together': {('instrument', 'definition')},
            },
        ),
    ]
