# Generated by Django 2.2.6 on 2020-04-21 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cdi_forms", "0068_auto_20200409_1841"),
        ("cdi_forms", "0068_auto_20200420_0633"),
    ]

    operations = []
