# Generated by Django 2.2.6 on 2020-04-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdi_forms', '0069_merge_20200421_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundinfo',
            name='caregiver_other',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
