# Generated by Django 2.2.6 on 2020-04-21 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdi_forms', '0069_auto_20200413_0757'),
        ('cdi_forms', '0069_merge_20200421_0638'),
    ]

    operations = [
    ]
