# Generated by Django 2.2.6 on 2020-05-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdi_forms', '0070_backgroundinfo_caregiver_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundinfo',
            name='prolific_pid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
