# Generated by Django 2.2.13 on 2020-06-10 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdi_forms', '0072_auto_20200506_1029'),
        ('cdi_forms', '0071_choices_choice_set_ko'),
    ]

    operations = [
    ]
