# Generated by Django 2.2.13 on 2020-06-12 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researcher_UI", "0053_study_backpage_boolean"),
        ("cdi_forms", "0073_merge_20200610_0733"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatStartingWord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="researcher_UI.instrument",
                    ),
                ),
                (
                    "instrument_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cdi_forms.InstrumentItem",
                    ),
                ),
            ],
            options={
                "ordering": ["instrument", "age"],
                "unique_together": {("instrument", "age")},
            },
        ),
    ]
