# Generated by Django 2.2.13 on 2020-07-26 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cdi_forms", "0074_catstartingword"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="instrumentitem",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="instrumentitem",
            name="instrument",
        ),
        migrations.DeleteModel(
            name="CatStartingWord",
        ),
        migrations.DeleteModel(
            name="InstrumentItem",
        ),
    ]
