# Generated by Django 2.2.13 on 2021-01-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdi_forms', '0076_auto_20210122_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundinfo',
            name='children_comforted',
            field=models.CharField(blank=True, choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('somewhat disagree', 'Somewhat Disagree'), ('neither agree no disagree', 'Neither Agree No Disagree'), ('somewhat agree', 'Somewhat Agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=51, null=True, verbose_name='Children should be comforted when they are scared or unhappy.'),
        ),
        migrations.AddField(
            model_name='backgroundinfo',
            name='close_bonds',
            field=models.CharField(blank=True, choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('somewhat disagree', 'Somewhat Disagree'), ('neither agree no disagree', 'Neither Agree No Disagree'), ('somewhat agree', 'Somewhat Agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=51, null=True, verbose_name='A child who has close bonds with his or her parents will have better relationships later onin life.'),
        ),
        migrations.AddField(
            model_name='backgroundinfo',
            name='do_as_told',
            field=models.CharField(blank=True, choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('somewhat disagree', 'Somewhat Disagree'), ('neither agree no disagree', 'Neither Agree No Disagree'), ('somewhat agree', 'Somewhat Agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=51, null=True, verbose_name='It is very important for young children to do as they are told, for example, waiting when they are told to wait.'),
        ),
        migrations.AddField(
            model_name='backgroundinfo',
            name='explore_experiment',
            field=models.CharField(blank=True, choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('somewhat disagree', 'Somewhat Disagree'), ('neither agree no disagree', 'Neither Agree No Disagree'), ('somewhat agree', 'Somewhat Agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=51, null=True, verbose_name='It is good to let children explore and experiment.'),
        ),
        migrations.AddField(
            model_name='backgroundinfo',
            name='parents_help_learn',
            field=models.CharField(blank=True, choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('somewhat disagree', 'Somewhat Disagree'), ('neither agree no disagree', 'Neither Agree No Disagree'), ('somewhat agree', 'Somewhat Agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=51, null=True, verbose_name='Parents can help babies learn language by talking to them.'),
        ),
        migrations.AddField(
            model_name='backgroundinfo',
            name='play_learning',
            field=models.CharField(blank=True, choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('somewhat disagree', 'Somewhat Disagree'), ('neither agree no disagree', 'Neither Agree No Disagree'), ('somewhat agree', 'Somewhat Agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=51, null=True, verbose_name='Babies can learn a lot just by playing.'),
        ),
        migrations.AddField(
            model_name='backgroundinfo',
            name='show_respect',
            field=models.CharField(blank=True, choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('somewhat disagree', 'Somewhat Disagree'), ('neither agree no disagree', 'Neither Agree No Disagree'), ('somewhat agree', 'Somewhat Agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=51, null=True, verbose_name='It is very important that children learn to respect adults, such as parents and teachers.'),
        ),
    ]
