# Generated by Django 2.2.13 on 2021-01-29 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdi_forms', '0078_auto_20210122_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundinfo',
            name='children_comforted',
        ),
    ]
