# Generated by Django 2.2.13 on 2021-04-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdi_forms', '0078_auto_20210122_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='choice_set_es_ar',
            field=models.CharField(max_length=101, null=True),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='child_self_reads',
            field=models.CharField(blank=True, choices=[('never', 'Never'), ('less than once/week', 'Less Than Once/Week'), ('once/week', 'Once/Week'), ('2-3 times/week', '2-3 Times/Week'), ('3-4 times/week', '3-4 Times/Week'), ('5-6 times/week', '5-6 Times/Week'), ('daily', 'Daily')], max_length=51, null=True, verbose_name='About how many times per week does your child look at books by themself?'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='children_comforted',
            field=models.CharField(blank=True, choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('somewhat disagree', 'Somewhat Disagree'), ('neither agree nor disagree', 'Neither Agree Nor Disagree'), ('somewhat agree', 'Somewhat Agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=51, null=True, verbose_name='Children should be comforted when they are scared or unhappy.'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='close_bonds',
            field=models.CharField(blank=True, choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('somewhat disagree', 'Somewhat Disagree'), ('neither agree nor disagree', 'Neither Agree Nor Disagree'), ('somewhat agree', 'Somewhat Agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=51, null=True, verbose_name='A child who has close bonds with his or her parents will have better relationships later on in life.'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='do_as_told',
            field=models.CharField(blank=True, choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('somewhat disagree', 'Somewhat Disagree'), ('neither agree nor disagree', 'Neither Agree Nor Disagree'), ('somewhat agree', 'Somewhat Agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=51, null=True, verbose_name='It is very important for young children to do as they are told, for example, waiting when they are told to wait.'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='explore_experiment',
            field=models.CharField(blank=True, choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('somewhat disagree', 'Somewhat Disagree'), ('neither agree nor disagree', 'Neither Agree Nor Disagree'), ('somewhat agree', 'Somewhat Agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=51, null=True, verbose_name='It is good to let children explore and experiment.'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='parents_help_learn',
            field=models.CharField(blank=True, choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('somewhat disagree', 'Somewhat Disagree'), ('neither agree nor disagree', 'Neither Agree Nor Disagree'), ('somewhat agree', 'Somewhat Agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=51, null=True, verbose_name='Parents can help babies learn language by talking to them.'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='play_learning',
            field=models.CharField(blank=True, choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('somewhat disagree', 'Somewhat Disagree'), ('neither agree nor disagree', 'Neither Agree Nor Disagree'), ('somewhat agree', 'Somewhat Agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=51, null=True, verbose_name='Babies can learn a lot just by playing.'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='show_respect',
            field=models.CharField(blank=True, choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('somewhat disagree', 'Somewhat Disagree'), ('neither agree nor disagree', 'Neither Agree Nor Disagree'), ('somewhat agree', 'Somewhat Agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=51, null=True, verbose_name='It is very important that children learn to respect adults, such as parents and teachers.'),
        ),
    ]
