# Generated by Django 2.2.13 on 2021-01-29 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdi_forms', '0079_remove_backgroundinfo_children_comforted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundinfo',
            name='show_respect',
        ),
    ]
