# Generated by Django 2.2.13 on 2021-01-29 08:09

from django.db import migrations
#import likert_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('cdi_forms', '0080_remove_backgroundinfo_show_respect'),
    ]

    operations = [
        '''
        migrations.AddField(
            model_name='backgroundinfo',
            name='children_comforted',
            field=likert_field.models.LikertField(blank=True, null=True, verbose_name='Children should be comforted when they are scared or unhappy.'),
        ),
        migrations.AddField(
            model_name='backgroundinfo',
            name='show_respect',
            field=likert_field.models.LikertField(blank=True, null=True, verbose_name='It is very important that children learn to respect adults, such as parents and teachers.'),
        ),
        '''
    ]
