# Generated by Django 2.2.13 on 2021-01-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdi_forms', '0081_auto_20210129_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundinfo',
            name='children_comforted',
            field=models.CharField(blank=True, choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('somewhat disagree', 'Somewhat Disagree'), ('neither agree no disagree', 'Neither Agree No Disagree'), ('somewhat agree', 'Somewhat Agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=51, null=True, verbose_name='Children should be comforted when they are scared or unhappy.'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='show_respect',
            field=models.CharField(blank=True, choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('somewhat disagree', 'Somewhat Disagree'), ('neither agree no disagree', 'Neither Agree No Disagree'), ('somewhat agree', 'Somewhat Agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=51, null=True, verbose_name='It is very important that children learn to respect adults, such as parents and teachers.'),
        ),
    ]
