# Generated by Django 3.2.18 on 2023-03-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdi_forms', '0086_alter_backgroundinfo_generic_health_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundinfo',
            name='primary_caregiver_occupation',
            field=models.CharField(blank=True, max_length=101, null=True, verbose_name='Primary caregiver occupation'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='primary_caregiver_occupation_description',
            field=models.CharField(blank=True, max_length=101, null=True, verbose_name='Primary caregiver occupation description'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='secondary_caregiver_occupation',
            field=models.CharField(blank=True, max_length=101, null=True, verbose_name='Secondary caregiver occupation'),
        ),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='secondary_caregiver_occupation_description',
            field=models.CharField(blank=True, max_length=101, null=True, verbose_name='Secondary caregiver occupation description'),
        ),
    ]
