# Generated by Django 3.2.18 on 2023-03-09 16:31

from django.db import migrations, models

from cdi_forms.models import BackgroundInfo

def remove_negatives(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    backgrounds = BackgroundInfo.objects.filter(sibling_count__lt=0)
    backgrounds.update(sibling_count=0)

class Migration(migrations.Migration):

    dependencies = [
        ('cdi_forms', '0087_auto_20230309_1630'),
    ]

    operations = [
        migrations.RunPython(remove_negatives),
        migrations.AlterField(
            model_name='backgroundinfo',
            name='sibling_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='How many siblings does you child have?'),
        ),
    ]
