# Generated by Django 3.2.19 on 2023-06-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cdi_forms", "0088_alter_backgroundinfo_sibling_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrument_forms",
            name="enable_response",
            field=models.CharField(blank=True, max_length=51, null=True),
        ),
        migrations.AddField(
            model_name="instrument_forms",
            name="enabler",
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
