# Generated by Django 4.2.11 on 2024-06-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cdi_forms", "0091_alter_backgroundinfo_father_yob_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="choices",
            name="choice_set_jp",
            field=models.CharField(max_length=101, null=True),
        ),
    ]
