# Generated by Django 4.2.11 on 2024-06-04 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cdi_forms", "0092_choices_choice_set_jp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choices",
            old_name="choice_set_jp",
            new_name="choice_set_ja",
        ),
    ]
