# Generated by Django 2.2.6 on 2020-03-31 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('researcher_UI', '0046_auto_20200331_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(blank=True, max_length=1001, null=True)),
                ('discrimination', models.FloatField()),
                ('difficulty', models.FloatField()),
                ('guessing', models.FloatField()),
                ('upper_asymptote', models.FloatField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher_UI.instrument')),
            ],
            options={
                'unique_together': {('instrument', 'definition')},
            },
        ),
    ]
