# Generated by Django 2.2.6 on 2020-03-31 11:47

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researcher_UI', '0046_auto_20200331_0829'),
        ('cat_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentitem',
            options={'ordering': ['definition']},
        ),
        migrations.CreateModel(
            name='CatResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administered_items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=101), size=None)),
                ('administered_responses', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), size=None)),
                ('administration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='researcher_UI.administration')),
            ],
        ),
    ]
