# Generated by Django 2.2.6 on 2020-03-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_forms', '0003_auto_20200331_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='catresponse',
            name='est_theta',
            field=models.FloatField(null=True),
        ),
    ]
