# Generated by Django 2.2.6 on 2020-03-31 18:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_forms', '0004_catresponse_est_theta'),
    ]

    operations = [
        migrations.AddField(
            model_name='catresponse',
            name='administered_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=101), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='catresponse',
            name='administered_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
