# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-28 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplementtut', '0002_myregistrationsupplement_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myregistrationsupplement',
            name='name',
        ),
        migrations.AddField(
            model_name='myregistrationsupplement',
            name='first_name',
            field=models.CharField(default='FirstName', max_length=101, verbose_name='First name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myregistrationsupplement',
            name='last_name',
            field=models.CharField(default='LastName', max_length=101, verbose_name='Last name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myregistrationsupplement',
            name='institution',
            field=models.CharField(max_length=101, verbose_name='Name of Institution'),
        ),
    ]
